server:
  port: 8181
  servlet:
    context-path: /customer
    
logging:
  file: 
    path: log
  level:
    local:
      demo:
        microservices:
          customer: DEBUG
    
spring:
  output:
    ansi:
      enabled: DETECT
  application:
    name: customer
  datasource:
    url: jdbc:postgresql://localhost:5432/springdb
    username: spring
    password: springpass
    driver-class-name: org.postgresql.Driver
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 10
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format:
          sql: true
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
#
# RabbitMQ
#         
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest        


rabbitmq:
  queue-name: test-queue
  exchange-name: test-exchange
  routing-key-name: test.path.#
  
  