server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri:  git@github.com:isaacgzdc/microservices-config.git
#          uri: file://${user.home}/devel/workspace/microservices/configuration
          skipSslValidation: true
          clone-on-start: true
