server:
  port: 9494
spring:
  cloud:
    config:
      server:
        git:
          uri:  git@github.com:isaacgzdc/microservices-config.git
#          clone-on-start: true
logging:
  level:
    web:
      property: 'DEBUG'